name: Android Build

on:
  push:
    branches:
      - main # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        yarn install

    - name: Run linting
      run: |
        npm run lint # ou o comando específico para rodar o seu linting, como ESLint

    - name: Run tests
      run: |
        npm test # ou o comando específico para rodar os seus testes

    - name: Build Android APK
      run: |
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
        cd android && ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
